/**
 * This class is generated by jOOQ
 */
package com.jugmontpellier.jooq.tables.daos;


import com.jugmontpellier.jooq.tables.Talk;
import com.jugmontpellier.jooq.tables.records.TalkRecord;

import java.sql.Timestamp;
import java.util.List;
import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TalkDao extends DAOImpl<TalkRecord, com.jugmontpellier.jooq.tables.pojos.Talk, UUID> {

	/**
	 * Create a new TalkDao without any configuration
	 */
	public TalkDao() {
		super(Talk.TALK, com.jugmontpellier.jooq.tables.pojos.Talk.class);
	}

	/**
	 * Create a new TalkDao with an attached configuration
	 */
	public TalkDao(Configuration configuration) {
		super(Talk.TALK, com.jugmontpellier.jooq.tables.pojos.Talk.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected UUID getId(com.jugmontpellier.jooq.tables.pojos.Talk object) {
		return object.getIdTalk();
	}

	/**
	 * Fetch records that have <code>id_talk IN (values)</code>
	 */
	public List<com.jugmontpellier.jooq.tables.pojos.Talk> fetchByIdTalk(UUID... values) {
		return fetch(Talk.TALK.ID_TALK, values);
	}

	/**
	 * Fetch a unique record that has <code>id_talk = value</code>
	 */
	public com.jugmontpellier.jooq.tables.pojos.Talk fetchOneByIdTalk(UUID value) {
		return fetchOne(Talk.TALK.ID_TALK, value);
	}

	/**
	 * Fetch records that have <code>title IN (values)</code>
	 */
	public List<com.jugmontpellier.jooq.tables.pojos.Talk> fetchByTitle(String... values) {
		return fetch(Talk.TALK.TITLE, values);
	}

	/**
	 * Fetch records that have <code>description IN (values)</code>
	 */
	public List<com.jugmontpellier.jooq.tables.pojos.Talk> fetchByDescription(String... values) {
		return fetch(Talk.TALK.DESCRIPTION, values);
	}

	/**
	 * Fetch records that have <code>date_ IN (values)</code>
	 */
	public List<com.jugmontpellier.jooq.tables.pojos.Talk> fetchByDate_(Timestamp... values) {
		return fetch(Talk.TALK.DATE_, values);
	}

	/**
	 * Fetch records that have <code>speaker_fk IN (values)</code>
	 */
	public List<com.jugmontpellier.jooq.tables.pojos.Talk> fetchBySpeakerFk(UUID... values) {
		return fetch(Talk.TALK.SPEAKER_FK, values);
	}
}
