
INSERT INTO "SPEAKER" (name_, mail, twitter) VALUES ('f70634a9-70f8-4792-bbd9-dd652362fe81', 'François Teychene', 'françois_teychene@gmail.com', '@François');
INSERT INTO "SPEAKER" (name_, mail, twitter) VALUES ('0953d8c8-4ea8-4859-adfa-3194c450ee16', 'Cyprien Pannier', 'cyprien_pannier@gmail.com', '@Cyprien');
INSERT INTO "SPEAKER" (name_, mail, twitter) VALUES ('df3b518d-7241-47aa-ace0-6a3baffeb388', 'Olivier Nouguier', 'olivier_nouguier@gmail.com', '@Olivier');
INSERT INTO "SPEAKER" (name_, mail, twitter) VALUES ('abd9ec9c-982d-488b-a497-e4560948858c', 'Anastasia Lieva', 'anastasia_lieva@gmail.com', '@Anastasia');
INSERT INTO "SPEAKER" (name_, mail, twitter) VALUES ('8a406758-cbff-4c82-9c65-768676dc5dbf', 'Thomas Girard', 'thomas_girard@gmail.com', '@Thomas');
INSERT INTO "SPEAKER" (name_, mail, twitter) VALUES ('b0aef670-be1c-4793-97f7-e2e2d7fb205d', 'Arnaud Castelltort', 'arnaud_castelltort@gmail.com', '@Arnaud');


INSERT INTO "TALK" (speaker_fk, date_, title, description) VALUES ('f70634a9-70f8-4792-bbd9-dd652362fe81', '2015-12-16 19:00', 'Setup un PAAS', 'Monter un PAAS sur un serveur a la maison.');
INSERT INTO "TALK" (speaker_fk, date_, title, description) VALUES ('0953d8c8-4ea8-4859-adfa-3194c450ee16', '2015-12-16 19:20', 'A microservice example with Clojure', 'Clojure is awesome :) De par sa nature fonctionnelle et immutable, il est très adapté pour manipuler de la donnée, il suffit de voir des projets open source tels que Storm. Mais c''est avant tout un langage très élégant et pragmatique qui vous permet d''écrire des micro-services robustes et extensibles. C''est ce que j''essaierai de démontrer au travers d''une application simple (pas encore décidé quoi), en partant de zéro, "codant" (ce ne sera pas du live coding !) et expliquant différents concepts clés au fur et à mesure (liste non fixée): * Bootstrap a Clojure project * How handle the configuration ? * The REPL is your friend * Extend existing java classes * Provide extension points the Clojure way * Test with clojure.test * Bonus: Clojure Component helps you maintain and test bigger projets');
INSERT INTO "TALK" (speaker_fk, date_, title, description) VALUES ('df3b518d-7241-47aa-ace0-6a3baffeb388', '2015-12-16 19:40', 'Category Theory', 'Rapide overview du sujet, ce qu''il faut en retenir pour aimer encore plus Scala :)');
INSERT INTO "TALK" (speaker_fk, date_, title, description) VALUES ('abd9ec9c-982d-488b-a497-e4560948858c', '2015-12-16 20:00', 'NUPIC : framework et nouveau concept d''intelligence artificielle', 'La plate-forme NuPic: http://numenta.org/ intro en HTM. un exemple de l''utilisation NuPic pour la prédiction/détection d''anomalie et les défis que pose Nupic');
INSERT INTO "TALK" (speaker_fk, date_, title, description) VALUES ('8a406758-cbff-4c82-9c65-768676dc5dbf', '2015-12-16 20:20', 'Oublie Junit, embarque avec Spock', 'Tu utilises Junit, TestNg, Mockito, jMock, EasyMock ou bien d''autres ? Vient découvrir Spock Framework autour d''une application Spring Boot. Nous verrons comment tester une application Java ou Groovy et les avantages apportés par le langage Groovy et Spock Framework dans la rédaction de tests unitaires.');
INSERT INTO "TALK" (speaker_fk, date_, title, description) VALUES ('b0aef670-be1c-4793-97f7-e2e2d7fb205d', '2015-12-16 20:40', 'MicroBenchmarking: a survival guide on JVM', 'What is MicroBenchmarking ? What are the problems with the dynamic compilation language, the usecase of the JVM The Heisenberg principle Statistics theory as a rigorous data analysis approach Scala Meter Sum-Up Survival Guide');
INSERT INTO "TALK" (speaker_fk, date_, title, description) VALUES ('b0aef670-be1c-4793-97f7-e2e2d7fb205d', '2015-12-16 21:00', 'Parser combinator in Scala', '');

