/**
 * This class is generated by jOOQ
 */
package com.jugmontpellier.jooq.tables.pojos;


import java.io.Serializable;
import java.util.UUID;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Speaker implements Serializable {

	private static final long serialVersionUID = 858076167;

	private UUID   idSpeaker;
	private String name_;
	private String mail;
	private String twitter;

	public Speaker() {}

	public Speaker(Speaker value) {
		this.idSpeaker = value.idSpeaker;
		this.name_ = value.name_;
		this.mail = value.mail;
		this.twitter = value.twitter;
	}

	public Speaker(
		UUID   idSpeaker,
		String name_,
		String mail,
		String twitter
	) {
		this.idSpeaker = idSpeaker;
		this.name_ = name_;
		this.mail = mail;
		this.twitter = twitter;
	}

	public UUID getIdSpeaker() {
		return this.idSpeaker;
	}

	public void setIdSpeaker(UUID idSpeaker) {
		this.idSpeaker = idSpeaker;
	}

	public String getName_() {
		return this.name_;
	}

	public void setName_(String name_) {
		this.name_ = name_;
	}

	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	public String getTwitter() {
		return this.twitter;
	}

	public void setTwitter(String twitter) {
		this.twitter = twitter;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("Speaker (");

		sb.append(idSpeaker);
		sb.append(", ").append(name_);
		sb.append(", ").append(mail);
		sb.append(", ").append(twitter);

		sb.append(")");
		return sb.toString();
	}
}
