/**
 * This class is generated by jOOQ
 */
package com.jugmontpellier.jooq;


import com.jugmontpellier.jooq.tables.Speaker;
import com.jugmontpellier.jooq.tables.Talk;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table public.SPEAKER
	 */
	public static final Speaker SPEAKER = com.jugmontpellier.jooq.tables.Speaker.SPEAKER;

	/**
	 * The table public.TALK
	 */
	public static final Talk TALK = com.jugmontpellier.jooq.tables.Talk.TALK;
}
