/**
 * This class is generated by jOOQ
 */
package com.jugmontpellier.jooq.tables.records;


import com.jugmontpellier.jooq.tables.Talk;

import java.sql.Timestamp;
import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TalkRecord extends UpdatableRecordImpl<TalkRecord> implements Record5<UUID, String, String, Timestamp, UUID> {

	private static final long serialVersionUID = -450648972;

	/**
	 * Setter for <code>public.TALK.id_talk</code>.
	 */
	public void setIdTalk(UUID value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.TALK.id_talk</code>.
	 */
	public UUID getIdTalk() {
		return (UUID) getValue(0);
	}

	/**
	 * Setter for <code>public.TALK.title</code>.
	 */
	public void setTitle(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.TALK.title</code>.
	 */
	public String getTitle() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>public.TALK.description</code>.
	 */
	public void setDescription(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.TALK.description</code>.
	 */
	public String getDescription() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>public.TALK.date_</code>.
	 */
	public void setDate_(Timestamp value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.TALK.date_</code>.
	 */
	public Timestamp getDate_() {
		return (Timestamp) getValue(3);
	}

	/**
	 * Setter for <code>public.TALK.speaker_fk</code>.
	 */
	public void setSpeakerFk(UUID value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.TALK.speaker_fk</code>.
	 */
	public UUID getSpeakerFk() {
		return (UUID) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<UUID> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<UUID, String, String, Timestamp, UUID> fieldsRow() {
		return (Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<UUID, String, String, Timestamp, UUID> valuesRow() {
		return (Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<UUID> field1() {
		return Talk.TALK.ID_TALK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Talk.TALK.TITLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return Talk.TALK.DESCRIPTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field4() {
		return Talk.TALK.DATE_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<UUID> field5() {
		return Talk.TALK.SPEAKER_FK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UUID value1() {
		return getIdTalk();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getTitle();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getDescription();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value4() {
		return getDate_();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UUID value5() {
		return getSpeakerFk();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TalkRecord value1(UUID value) {
		setIdTalk(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TalkRecord value2(String value) {
		setTitle(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TalkRecord value3(String value) {
		setDescription(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TalkRecord value4(Timestamp value) {
		setDate_(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TalkRecord value5(UUID value) {
		setSpeakerFk(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TalkRecord values(UUID value1, String value2, String value3, Timestamp value4, UUID value5) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TalkRecord
	 */
	public TalkRecord() {
		super(Talk.TALK);
	}

	/**
	 * Create a detached, initialised TalkRecord
	 */
	public TalkRecord(UUID idTalk, String title, String description, Timestamp date_, UUID speakerFk) {
		super(Talk.TALK);

		setValue(0, idTalk);
		setValue(1, title);
		setValue(2, description);
		setValue(3, date_);
		setValue(4, speakerFk);
	}
}
